Reset scroll position when switching tabs
snapcrunch/electron-preferences pull request #159
Opened 2022-04-13 09:55 UTC by serotonyn

Hi, here's my pull request 

https://github.com/snapcrunch/electron-preferences/issues/158#issue-1199123483

2022-04-13 12:23 UTC, lacymorrow requested changes

2022-04-13 12:23 UTC, lacymorrow commented on src/app/components/main/index.jsx
> +		console.log('ho');
Looks good! Just lose this comment and I'll approve

2022-04-14 08:37 UTC, serotonyn commented on src/app/components/main/index.jsx
> +		console.log('ho');
I just did, thank you !

2022-04-14 09:50 UTC, pvrobays requested changes
Could you also add this feature to the CHANGELOG.md?

2022-04-14 09:50 UTC, pvrobays commented on src/app/components/main/index.jsx
> +		this.mainRef.current.scrollTo({ top: 0 });
I don't think it's a good idea to trigger the scrollToTop within the `componentDitUpdate`.
React will trigger this way more than only when the active section changes.

Just tested this. React even triggers the `componentDidUpdate` when changing input fields within the group.

2022-04-14 11:27 UTC, serotonyn commented on src/app/components/main/index.jsx
> +		this.mainRef.current.scrollTo({ top: 0 });
My bad, I should've tested before committing. I added a guard to make sure we only reset the scroll when `activeSection` changes.

2022-04-14 11:38 UTC, serotonyn commented
> Hi @serotonyn Thanks for your contribution. Much appreciated!
> 
> Could you also add this feature to the CHANGELOG.md?

Hey @pvrobays, thanks for the review. I just update the changelog. Hope it's okay now !

2022-04-14 12:21 UTC, pvrobays commented on src/app/components/main/index.jsx
> +		super();
```suggestion
	constructor(props) {

		super(props);
```

2022-04-15 04:06 UTC, serotonyn commented on src/app/components/main/index.jsx
> +		super();
Based on [this article by Dan Abramov](https://overreacted.io/why-do-we-write-super-props/), it's recommended to always pass `props`, even though it's not strictly necessary in this situation since we're not using them inside the constructor.

2022-04-26 10:32 UTC, pvrobays commented on src/app/components/main/index.jsx
> +		super();
TIL: React calls `instance.props = props` after init! 😉

2022-04-26 10:32 UTC, merged

2022-04-26 10:35 UTC, pvrobays commented
Thanks for the contribution @serotonyn !

2022-05-02 21:20 UTC, serotonyn commented
Thanks for the review!